title: Home Server
color: slate
headerStyle: boxed

layout:
  Media:
    style: columns
  Downloads:
    style: columns
  Cloud:
    style: columns
  System:
    style: columns
  Background:
    style: columns
