networks:
  default:
    name: homelab_net
    external: true

services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    labels:
      kuma.jellyfin.docker.name: jellyfin
    runtime: nvidia
    ports:
      - "8096:8096"
      - "8920:8920"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - UMASK=${UMASK}
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
    volumes:
      - /mnt/user/appdata/jellyfin:/config
      - /mnt/user/data/media:/data/media
      - /mnt/user/appdata/jellyfin/cache/transcodes:/config/cache/transcodes
    restart: unless-stopped

  jellyseerr:
    image: ghcr.io/seerr-team/seerr:latest
    container_name: jellyseerr
    labels:
      kuma.jellyseerr.docker.name: jellyseerr
    init: true
    user: "1000:1000"
    ports:
      - "5055:5055"
    environment:
      - TZ=${TZ}
    volumes:
      - /mnt/user/appdata/jellyseerr:/app/config
    restart: unless-stopped

  tdarr:
    image: ghcr.io/haveagitgat/tdarr:latest
    container_name: tdarr
    labels:
      kuma.tdarr.docker.name: tdarr
    ports:
      - "8265:8265"
      - "8266:8266"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - UMASK_SET=${UMASK}
      - serverIP=0.0.0.0
      - serverPort=8266
      - webUIPort=8265
      - internalNode=false
      - inContainer=true
      - ffmpegVersion=7
    volumes:
      - /mnt/user/appdata/tdarr/server:/app/server
      - /mnt/user/appdata/tdarr/configs:/app/configs
      - /mnt/user/appdata/tdarr/logs:/app/logs
      - /mnt/user/data/media:/media
    restart: unless-stopped

  tdarr-node:
    image: ghcr.io/haveagitgat/tdarr_node:latest
    container_name: tdarr-node
    labels:
      kuma.tdarr-node.docker.name: tdarr-node
    network_mode: service:tdarr
    runtime: nvidia
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - UMASK_SET=${UMASK}
      - nodeName=UnraidNode
      - serverIP=0.0.0.0
      - serverPort=8266
      - inContainer=true
      - ffmpegVersion=7
      - transcodegpuWorkers=1
      - transcodecpuWorkers=2
      - healthcheckgpuWorkers=1
      - healthcheckcpuWorkers=1
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
    volumes:
      - /mnt/user/appdata/tdarr/configs:/app/configs
      - /mnt/user/appdata/tdarr/logs:/app/logs
      - /mnt/user/appdata/tdarr/transcode_cache:/temp
      - /mnt/user/data/media:/media
    restart: unless-stopped

